[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'

#[[plugins]]
#repo = 'vim-airline/vim-airline'
#hook_add = 'souce ~/.config/nvim/rc/plugins/vim-airline.vim'

#[[plugins]]
#repo = 'vim-airline/vim-airline-theme'


[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/rc/plugins/vim-gitgutter.vim'


[[plugins]]
repo = 'rking/ag.vim'
hook_add = 'source ~/.config/nvim/rc/plugins/search.vim'

[[plugins]]
repo = 'sbdchd/neoformat'
hook_add = 'source ~/.config/nvim/rc/plugins/neoformat.vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add ='source ~/.config/nvim/rc/plugins/startify.vim'


[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.config/nvim/rc/plugins/indentline.vim'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/rc/plugins/vim-ale.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install'
hook_add = '''
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'

source ~/.config/nvim/rc/plugins/allkey.vim
'''

