[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'sbdchd/neoformat'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'yarn install'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
